# Generated by Django 6.0.3 on 2026-03-10 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Entradas", "Entradas"),
                            ("Sopas", "Sopas"),
                            ("Carne", "Carne"),
                            ("Peixe", "Peixe"),
                            ("Sobremesa", "Sobremesa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("ingredients", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Order Preview", "Order Preview"),
                            ("Preparing", "Preparing"),
                            ("Cooling Down", "Cooling Down"),
                            ("Ready to Serve", "Ready to Serve"),
                            ("Concluded", "Concluded"),
                        ],
                        default="Order Preview",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.menuitem"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="api.order",
                    ),
                ),
            ],
        ),
    ]
